In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("locales.csv")

In [3]:
data

,nombre,direccion,codigo_postal,puntuacion_media,numero_reviews,tipo_negocio,latitud,longitud
0,Madrid,Madrid,28004,NaN,NaN,"locality, political",40.416728,-3.703291
1,Hotel Infantas by Mij,"Calle de las Infantas, 29, Madrid",28004,4.2,835.0,"lodging, point_of_interest, establishment",40.420107,-3.697054
2,Petit Palace Triball,"Calle Gonzalo Jiménez de Quesada, 2, Madrid",28004,4.5,1726.0,"lodging, point_of_interest, establishment",40.420565,-3.702908
3,INNSiDE by Meliá Madrid Gran Vía,"Calle de Mesonero Romanos, 13, Madrid",28004,4.3,1801.0,"lodging, point_of_interest, establishment",40.420612,-3.703958
4,Hotel Regina Madrid,"Calle Alcalá, 19, Madrid",28004,4.5,2710.0,"lodging, point_of_interest, establishment",40.417913,-3.699877
...,...,...,...,...,...,...,...,...
336,Restaurante La Playa,"Calle de Magallanes, 24, Madrid",28015,4.1,622.0,"restaurant, point_of_interest, food, establish...",40.433518,-3.705484
337,AIRE'S PELUQUERÍA Y BELLEZA,"Calle de Alberto Aguilera, 11, Madrid",28015,4.7,264.0,"hair_care, beauty_salon, point_of_interest, es...",40.429725,-3.708549
338,Hertz Alquiler De Coches - Madrid - Princesa,"Calle De La Princesa, 9 Returns, Calle de la P...",28015,2.8,140.0,"car_rental, point_of_interest, establishment",40.425574,-3.712777
339,Centro Quiropráctico Madrid,"Calle de Blasco de Garay, 12, Local, Madrid",28015,4.8,256.0,"physiotherapist, doctor, point_of_interest, he...",40.431018,-3.711503
340,Vincent Dental,"Calle de Amaniel, 29, Madrid",28015,5.0,12.0,"point_of_interest, health, establishment",40.427441,-3.709620

In [4]:
def type_of_establishment(name):
    name = name.lower()
    
    # Specific categories with multiple keywords
    if "hotel" in name or "lodging" in name:
        return "Hotel"
    elif "restaurant" in name or "restaurante" in name or "meal_takeaway" in name or "cafe" in name or "food" in name:
        return "Restaurant"
    elif "bar" in name:
        return "Bar"
    elif "car_rental" in name or "car_dealer" in name or "car_repair" in name:
        return "Automotive Services"
    elif "hospital" in name or "doctor" in name or "health" in name or "physiotherapist" in name:
        return "Health Services"
    elif "hair_care" in name or "beauty_salon" in name:
        return "Beauty Services"
    elif "school" in name or "university" in name:
        return "Education"
    elif "church" in name or "place_of_worship" in name:
        return "Religious Institution"
    elif "store" in name or "supermarket" in name or "book_store" in name or "electronics_store" in name or "clothing_store" in name or "home_goods_store" in name:
        return "Retail"
    elif "spa" in name:
        return "Spa"
    elif "parking" in name:
        return "Parking"
    elif "tourist_attraction" in name or "museum" in name or "art_gallery" in name or "library" in name:
        return "Tourist Attraction"
    elif "gas_station" in name or "convenience_store" in name:
        return "Gas Station"
    elif "finance" in name or "bank" in name or "atm" in name:
        return "Financial Services"
    elif "veterinary_care" in name:
        return "Veterinary Services"
    elif "laundry" in name:
        return "Laundry"
    elif "general_contractor" in name or "painter" in name:
        return "Contractor Services"
    elif "cemetery" in name:
        return "Cemetery"
    elif "movie_theater" in name:
        return "Entertainment"
    elif "local_government_office" in name:
        return "Government Services"
    elif "storage" in name:
        return "Storage Services"
    
    # Fallback for unclassified establishments
    return "Other"

In [5]:
data["tipo"] = data["nombre"].apply(type_of_establishment)

In [6]:
data.tipo.value_counts()

tipo
Other                    176
Hotel                    135
Restaurant                10
Spa                        6
Religious Institution      3
Education                  3
Storage Services           2
Health Services            2
Bar                        1
Financial Services         1
Cemetery                   1
Tourist Attraction         1
Name: count, dtype: int64

In [7]:
filttered_df = data[data["tipo"] == "Other"]

In [8]:
filttered_df

,nombre,direccion,codigo_postal,puntuacion_media,numero_reviews,tipo_negocio,latitud,longitud,tipo
0,Madrid,Madrid,28004,NaN,NaN,"locality, political",40.416728,-3.703291,Other
2,Petit Palace Triball,"Calle Gonzalo Jiménez de Quesada, 2, Madrid",28004,4.5,1726.0,"lodging, point_of_interest, establishment",40.420565,-3.702908,Other
3,INNSiDE by Meliá Madrid Gran Vía,"Calle de Mesonero Romanos, 13, Madrid",28004,4.3,1801.0,"lodging, point_of_interest, establishment",40.420612,-3.703958,Other
11,Eurostars Madrid Gran Vía,"Calle de Leganitos, 13, Madrid",28004,4.1,1375.0,"lodging, point_of_interest, establishment",40.421215,-3.709912,Other
12,Hostal Puerta del Sol,"Puerta del Sol, 14, Madrid",28004,4.0,276.0,"lodging, point_of_interest, establishment",40.417154,-3.702530,Other
...,...,...,...,...,...,...,...,...,...
335,Elipsos Internacional,"Calle de Alberto Aguilera, 7, Madrid",28015,4.3,4.0,"point_of_interest, establishment",40.429575,-3.708136,Other
337,AIRE'S PELUQUERÍA Y BELLEZA,"Calle de Alberto Aguilera, 11, Madrid",28015,4.7,264.0,"hair_care, beauty_salon, point_of_interest, es...",40.429725,-3.708549,Other
338,Hertz Alquiler De Coches - Madrid - Princesa,"Calle De La Princesa, 9 Returns, Calle de la P...",28015,2.8,140.0,"car_rental, point_of_interest, establishment",40.425574,-3.712777,Other
339,Centro Quiropráctico Madrid,"Calle de Blasco de Garay, 12, Local, Madrid",28015,4.8,256.0,"physiotherapist, doctor, point_of_interest, he...",40.431018,-3.711503,Other
340,Vincent Dental,"Calle de Amaniel, 29, Madrid",28015,5.0,12.0,"point_of_interest, health, establishment",40.427441,-3.709620,Other

In [9]:
filttered_df.tipo_negocio.value_counts()

tipo_negocio
lodging, point_of_interest, establishment                                             73
point_of_interest, establishment                                                      17
restaurant, point_of_interest, food, establishment                                    10
locality, political                                                                    7
sublocality_level_1, sublocality, political                                            5
general_contractor, point_of_interest, establishment                                   5
bar, restaurant, point_of_interest, food, establishment                                3
movie_theater, point_of_interest, establishment                                        2
restaurant, food, point_of_interest, establishment                                     2
meal_takeaway, restaurant, food, point_of_interest, establishment                      2
store, point_of_interest, establishment                                                2
church, place_of_worship, point_of_interest, establishment                             2
lodging, cafe, restaurant, point_of_interest, food, store, establishment               2
lodging, restaurant, food, point_of_interest, establishment                            2
electronics_store, store, point_of_interest, establishment                             1
hair_care, beauty_salon, point_of_interest, establishment                              1
parking, lodging, restaurant, point_of_interest, food, establishment                   1
lodging, spa, restaurant, point_of_interest, food, establishment                       1
physiotherapist, doctor, point_of_interest, health, establishment                      1
lodging, bar, point_of_interest, establishment                                         1
tourist_attraction, art_gallery, library, museum, point_of_interest, establishment     1
car_rental, point_of_interest, establishment                                           1
supermarket, grocery_or_supermarket, store, point_of_interest, food, establishment     1
book_store, store, point_of_interest, establishment                                    1
hospital, doctor, point_of_interest, health, establishment                             1
electronics_store, finance, jewelry_store, store, point_of_interest, establishment     1
laundry, point_of_interest, establishment                                              1
clothing_store, store, point_of_interest, establishment                                1
bar, point_of_interest, establishment                                                  1
hospital, point_of_interest, health, establishment                                     1
restaurant, cafe, bar, store, point_of_interest, food, establishment                   1
bank, finance, point_of_interest, establishment                                        1
lodging, spa, point_of_interest, food, establishment                                   1
health, point_of_interest, establishment                                               1
tourist_attraction, point_of_interest, establishment                                   1
restaurant, lodging, food, point_of_interest, establishment                            1
parking, lodging, restaurant, food, point_of_interest, establishment                   1
spa, lodging, food, point_of_interest, establishment                                   1
spa, lodging, restaurant, food, point_of_interest, establishment                       1
lodging, clothing_store, point_of_interest, store, establishment                       1
spa, lodging, point_of_interest, food, establishment                                   1
restaurant, lodging, point_of_interest, food, establishment                            1
lodging, restaurant, point_of_interest, food, establishment                            1
bar, lodging, point_of_interest, establishment                                         1
finance, point_of_interest, establishment                                              1
gas_station, convenience_store, point_of_interest, food, store, establishment          1
gas_station, point_of_interest, store, establishment                                   1
point_of_interest, doctor, health, establishment                                       1
point_of_interest, food, store, establishment                                          1
car_repair, point_of_interest, establishment                                           1
painter, point_of_interest, establishment                                              1
car_dealer, store, point_of_interest, establishment                                    1
home_goods_store, store, point_of_interest, establishment                              1
local_government_office, point_of_interest, establishment                              1
clothing_store, lodging, store, point_of_interest, establishment                       1
point_of_interest, health, establishment                                               1
Name: count, dtype: int64